Algoritmo "exemplo"

Var
   nome: caractere
   idade, anoAtual, anoNascimento: inteiro

Inicio
   // Passo 1: Entrada de dados
   Escreva("Digite seu nome: ")
   Leia(nome)

   Escreva("Digite sua idade: ")
   Leia(idade)

   // Passo 2: Processamento de dados
   anoAtual <- 2025
   anoNascimento <- anoAtual - idade

   // Passo 3: Saída de dados
   Escreval("Seu nome é ", nome, ".")
   Escreval("Você nasceu no ano de ", anoNascimento, ".")

Fimalgoritmo
